version: "3.9"

services:
  backend:
    build:
      context: .
      args:
        SQLALCHEMY_DATABASE_URL: mysql+pymysql://root:secret@database:3306/backend
    depends_on:
      - database
    ports:
      - 80:80
  database:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: backend
    ports:
    - 3306:3306

volumes:
  data:
