site_name: Full-Power Backend
theme:
  name: material
  palette:
    primary: blue
  favicon: images/favicon.png
  logo: images/favicon.png
  features:
    - navigation.instant

nav:
  - Backend: index.md
  - Getting started: first-steps.md
  - Settings: settings.md
  - Database: database.md
  - Scripts:
      - Scripts intro: scripts/scripts.md
      - check-db-connection: scripts/check-db-connection.md
      - clean-after-pr: scripts/clean-after-pr.md
      - create-first-admin: scripts/create-first-admin.md
      - create-scripts-docs: scripts/create-scripts-docs.md
      - release-changelog: scripts/release-changelog.md
      - update-questions: scripts/update-questions.md
  - Deploy:
      - Generic deploy: deploy/generic.md
      - O2Switch deploy: deploy/deploy-o2switch.md
  - Develop: develop.md
  - Troubleshoot: troubleshoot.md
  - Technical:
      - Technical intro: technical/index.md
      - HealthData algorithm: technical/hd-algorithm.md
      - HealthData algorithm examples: technical/hd-algorithm-examples.md
  - Build the docs: build-docs.md
  - Changelog: changelog.md
  - Contributing: contributing.md

repo_url: https://github.com/BelinguoAG/full-power-backend
repo_name: full-power-backend

extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/config.js
  - js/custom.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - attr_list
  - codehilite
  - extra
  - extra
  - footnotes
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: 🔗
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
