"""Add user.survey_filled and user.accepted_disclaimer

Revision ID: 1bb773fc366b
Revises: 6c0875021cd6
Create Date: 2021-02-12 17:41:13.403664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb773fc366b'
down_revision = '6c0875021cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accepted_disclaimer', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('survey_filled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'survey_filled')
    op.drop_column('users', 'accepted_disclaimer')
    # ### end Alembic commands ###
