"""add user.last_login

Revision ID: 3946494f961e
Revises: 796a148a7256
Create Date: 2020-12-29 14:48:27.261131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3946494f961e'
down_revision = '796a148a7256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_push-tokens_id', table_name='push-tokens')
    op.drop_table('push-tokens')
    op.add_column('users', sa.Column('last_login', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.create_table('push-tokens',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('token_json', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='push-tokens_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_push-tokens_id', 'push-tokens', ['id'], unique=False)
    # ### end Alembic commands ###
