"""Give more memory to Conversation's user and bot msg

Revision ID: 603d805b8dba
Revises: 1bb773fc366b
Create Date: 2021-03-02 11:37:17.367471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "603d805b8dba"
down_revision = "1bb773fc366b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("conversations", "user_msg", existing_type=sa.String(200), type_=sa.String(300))
    op.alter_column("conversations", "bot_msg", existing_type=sa.String(200), type_=sa.String(300))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("conversations", "user_msg", existing_type=sa.String(300), type_=sa.String(200))
    op.alter_column("conversations", "bot_msg", existing_type=sa.String(300), type_=sa.String(200))
    # ### end Alembic commands ###
